apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: zabbix-mysql-server
  name: zabbix-mysql-server
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mysql-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mysql-server
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-server
        resources: {}
        args: ["--character-set-server=utf8", "--collation-server=utf8_bin", "--default-authentication-plugin=mysql_native_password"]
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: zabbix-mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: zabbix-mysql-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: zabbix-mysql-config
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: zabbix-mysql-config
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-config-volume 
          mountPath: /etc/mysql/conf.d/default_auth.cnf ## path to mount file
          subPath: default_auth
      volumes:
        - name: mysql-config-volume 
          configMap:
            name: zabbix-mysql-config

status: {}
